/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    QuoteProofRegistry: {
      address: "0xa1a741aF6e0A45164e2Af6A1C35dC30275629709",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "oracle_",
              type: "address",
            },
            {
              internalType: "uint8",
              name: "expectedDecimals_",
              type: "uint8",
            },
            {
              internalType: "uint64",
              name: "maxAge_",
              type: "uint64",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "FutureObservation",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAnswer",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidCents",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidFeedDescription",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidMaxAge",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidObservationTime",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidOracle",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidRound",
          type: "error",
        },
        {
          inputs: [],
          name: "OracleReadFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "actual",
              type: "uint256",
            },
          ],
          name: "PreviewNonceChanged",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint80",
              name: "expected",
              type: "uint80",
            },
            {
              internalType: "uint80",
              name: "actual",
              type: "uint80",
            },
          ],
          name: "PreviewRoundChanged",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "age",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxAge",
              type: "uint256",
            },
          ],
          name: "StaleObservation",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "actual",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "expected",
              type: "uint8",
            },
          ],
          name: "UnexpectedDecimals",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "commitment",
              type: "bytes32",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "schemaVersion",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "chainId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "registry",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "issuer",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "nonce",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "cents",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "oracle",
                  type: "address",
                },
                {
                  internalType: "bytes32",
                  name: "feedId",
                  type: "bytes32",
                },
                {
                  internalType: "uint80",
                  name: "roundId",
                  type: "uint80",
                },
                {
                  internalType: "uint256",
                  name: "price",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "decimals",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "observedAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "recordedAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maximumAge",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "tinybars",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct QuoteProofRegistry.QuoteData",
              name: "quote",
              type: "tuple",
            },
          ],
          name: "QuoteRecorded",
          type: "event",
        },
        {
          inputs: [],
          name: "FEED_ID",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_CENTS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_ORACLE_DECIMALS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_CENTS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SCHEMA_VERSION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "cents",
              type: "uint256",
            },
            {
              internalType: "uint80",
              name: "expectedRound",
              type: "uint80",
            },
            {
              internalType: "uint256",
              name: "expectedNonce",
              type: "uint256",
            },
          ],
          name: "createQuote",
          outputs: [
            {
              internalType: "bytes32",
              name: "commitment",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "expectedDecimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
          ],
          name: "getCommitment",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "commitment",
              type: "bytes32",
            },
          ],
          name: "isStoredCommitment",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "maxAge",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
          ],
          name: "nonces",
          outputs: [
            {
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "oracle",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "cents",
              type: "uint256",
            },
          ],
          name: "previewQuote",
          outputs: [
            {
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
            {
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "decimals",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "observedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "tinybars",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40791768,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
