name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run hardhat:compile

      - name: Check Hardhat typings
        run: npm run hardhat:check-types

      - name: Run Hardhat tests
        run: npm run hardhat:test

      - name: Run nextjs lint
        run: npm run next:lint -- --max-warnings=0

      - name: Check typings on nextjs
        run: npm run next:check-types

      - name: Run hardhat lint
        run: npm run hardhat:lint -- --max-warnings=0

      - name: Build nextjs app
        run: npm run next:build
